# Generated by Django 3.2.6 on 2021-08-27 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizzeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sauce',
            name='name',
            field=models.CharField(default='', max_length=63),
        ),
        migrations.AddField(
            model_name='sauce',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shape',
            name='name',
            field=models.CharField(default='', max_length=63),
        ),
        migrations.AddField(
            model_name='shape',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
